# Site settings
# These are used to personalize your new site.
title: Paul McGlothlin # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  <br />In partial fulfillment of the requirements for the degree of Bachelor of Arts in Computer and Information Sciences (class of 2022).<br />
  <br />
  <a href="https://csuniv.joinhandshake.com/users/25814658">View My Handshake Profile</a>
  <br />
  [View My Resume](/pdf/paul_resume.pdf)
  <br />
repository: "paulryanmc/paulryanmc.github.io"
github_username:  paulryanmc # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

